#ifndef XEON_LOG_HH
#define XEON_LOG_HH

#include "soil/Log.hh"

#define XEON_LOG_INIT(x) SOIL_LOG_INIT(x)

#define XEON_TRACE SOIL_TRACE
#define XEON_DEBUG SOIL_DEBUG
#define XEON_INFO  SOIL_INFO
#define XEON_WARNING SOIL_WARNING
#define XEON_ERROR SOIL_ERROR
#define XEON_FATAL SOIL_FATAL
#define XEON_PDU SOIL_PDU
#define XEON_CUSTOM SOIL_CUSTOM


#endif

